### ISSUE TITLE
SyntaxError: await is only valid in async function [db.preparePromisified]

### ISSUE THREAD

**Issue by prakritidev** [SAP-samples/hana-hdbext-promisfied-example#1]
Hi, 

I was trying this module in my node.js application, below is the code and error for your reference. 
Am I doing something wrong here ? 

**CODE:**
```
app.get("/", (req, res) => {
	try {
		const dbClass = require("sap-hdbext-promisfied")
		let db = new dbClass(req.db);
		const statement = await db.preparePromisified(`SELECT SESSION_USER, CURRENT_SCHEMA FROM "DUMMY"`)
		const results = await db.statementExecPromisified(statement, [])
		let result = JSON.stringify({
			Objects: results
		})
		return res.type("application/json").status(200).send(result)
	} catch (e) {
		return res.type("text/plain").status(500).send(`ERROR: ${e.toString()}`)
	}
});
```

**Error Stack:** 

```
/home/vcap/app/server.js:89
const statement = await db.preparePromisified(`SELECT SESSION_USER, CURRENT_SCHEMA FROM "DUMMY"`)
^^^^^
SyntaxError: await is only valid in async function
at Module._compile (internal/modules/cjs/loader.js:723:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
at startup (internal/bootstrap/node.js:283:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm
ERR! code ELIFECYCLE
npm ERR! errno 1
npm
ERR! express-api-server@1.0.0 start: `node server.js`
```

**Comment by prakritidev** [comment]
Sorry, I forgot the async keyword.
